databases:
  - name: Love_Idle_DB
    databaseName: love_idle_db
    user: Love_Idle
    region: singapore

services:
  - type: web
    name: Love_Idle
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Love_Idle_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false